print("nebuus labi....")
print("porgramma pieprasa figūras elementus un aprēkina to laukumu")
print('nospiediet burtu:')
print("T - ja figura ir trijstūris")
print('tr - ja trapece')
print('p - ja figūra ir paralelograms')
print('ta - ja figura ir taisnstūris')
print('k - ja figura ir kvadrāts')
print('R -  ja figūra ir riņķis')
print('_________________________________________________________')
